# This file was generated by GoReleaser. DO NOT EDIT.
cask "timeout" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "d53c447e26bb9594737e17cd2bed0b271fa8bc9c98726001e3df6beeff0269f6"
      url "https://github.com/4thel00z/timeout/releases/download/v#{version}/timeout_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5502cfae817a81a5f61eced194d8d199e6aaa826fa767fc7bf133d55b2b742bf"
      url "https://github.com/4thel00z/timeout/releases/download/v#{version}/timeout_darwin_amd64.tar.gz"
    end
  end

  name "timeout"
  desc "GNU-compatible timeout for macOS"
  homepage "https://github.com/4thel00z/timeout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "timeout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/timeout"]
    end
  end

  # No zap stanza required
end
