# This file was generated by GoReleaser. DO NOT EDIT.
cask "timeout" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "2490b0d494270f4c362914aa8d3d44a757668da20e7b6cc8abbdacad600c2b07"
      url "https://github.com/4thel00z/timeout/releases/download/v#{version}/timeout_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d4c7f6402aeeebc0351017b7b4cd263c5d7d77143e2857e0e4c504d85da0e7c2"
      url "https://github.com/4thel00z/timeout/releases/download/v#{version}/timeout_darwin_amd64.tar.gz"
    end
  end

  name "timeout"
  desc "GNU-compatible timeout for macOS"
  homepage "https://github.com/4thel00z/timeout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "timeout"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/timeout"]
    end
  end

  # No zap stanza required
end
